flowchart TD
    USER[Cliente / Bruno / Insomnia] --> LB[Ingress NGINX / Load Balancer]

    LB --> API[fiapx API]
    LB --> GRAFANA[Grafana /grafana]

    API --> RABBIT[(RabbitMQ)]
    API --> S3[(S3 - vídeos e frames)]
    API --> RDS[(RDS PostgreSQL)]

    RABBIT --> WORKER[fiapx-ms-processing]
    WORKER --> S3
    WORKER --> API

    PROM[Prometheus] --> API
    PROM --> WORKER
    PROM --> RABBIT
    GRAFANA --> PROM

    subgraph AWS["AWS"]
      subgraph VPC["VPC"]
        subgraph EKS["EKS Cluster"]
          LB
          API
          WORKER
          PROM
          GRAFANA
        end
        RABBIT
        RDS
      end
      S3
      ECR[(ECR - fiapx / fiapx-ms-processing)]
    end

    GH[GitHub Actions] --> TF[Terraform / kubectl / Helm]
    GH --> ECR
    TF --> EKS
